export default {
    filemap: {
        "js": "JavaScript",
        "ts": "TypeScript",
        "py": "Python",
        "rb": "Ruby",
        "php": "PHP",
        "html": "HTML",
        "css": "CSS",
        "json": "JSON",
        "xml": "XML",
        "txt": "Text",
        "md": "Markdown",
        "go": "Go",
        "java": "Java",
        "c": "C",
        "cpp": "C++",
        "cs": "C#",
        "scala": "Scala",
        "sh": "Shell",
        "bat": "Batchfile",
        "r": "R",
        "swift": "Swift",
        "kt": "Kotlin",
        "rs": "Rust",
        "lua": "Lua",
        "pl": "Perl",
        "rb": "Ruby",
        "vb": "Visual Basic",
        "vbs": "Visual Basic Script",
        "f90": "Fortran",
        "f95": "Fortran",
        "f77": "Fortran",
        "f": "Fortran",
        "pas": "Pascal",
        "d": "D",
        "m": "Matlab",
        "matlab": "Matlab",
        "mlab": "Matlab",
        "ml": "OCaml",
        "ml4": "OCaml",
        "mli": "OCaml",
        "mll": "OCaml",
        "mly": "OCaml",
        "mlw": "OCaml",
        "mlc": "OCaml",
        "mla": "OCaml",
        "vue": "Vue",
        "scss": "SCSS",
        "sass": "SASS",
        "less": "Less",
        "stylus": "Stylus",
        "styl": "Stylus",
        "postcss": "PostCSS",
        "pcss": "PostCSS",
        "sql": "SQL",
        "sqlite": "SQL",
        "sqlite3": "SQL",
        "yml": "YAML",
        "yaml": "YAML",
        "conf": "Configuration",
        "ini": "Configuration",
        "cfg": "Configuration",
        "toml": "TOML",
        "ipynb": "Interactive Python Notebook"
    }
}